# main.py
# Entry point for the Firewall Rule Optimization GA.
# Run this file to execute the full pipeline.

import json
from ga.engine import run_ga
from visualizer.dashboard import show_dashboard


def main():
    # Step 1: Load test packets generated by simulator/packets.py
    with open("data/sample_packets.json", "r") as f:
        packets = json.load(f)

    # Step 2: Run the GA (200 generations, population of 50)
    print("Starting GA...")
    results = run_ga(packets, population_size=50, generations=200)

    # Step 3: Print the best firewall found
    best = results["best_chromosome"]
    print(f"\nBest firewall found ({len(best.rules)} rules):")
    for rule in best.rules:
        print(f"  {rule}")

    # Step 4: Show the dashboard
    show_dashboard(results["history"])


if __name__ == "__main__":
    main()